### PR TITLE
To dolist structure

### PR DESCRIPTION
**Pull request by SSEKPIUS**
In this project, I will build a simple HTML list of To Do tasks. The list will be styled according to the specifications listed later in this lesson. This simple web page will be built using webpack and served by a webpack dev server.

### CODE REVIEW

**Review by tresorsawasawa — APPROVED** [review]
Hi @SSEKPIUS 

Sorry, this is here by error. I mistakenly click the wrong button to submit your review. The correct review is below.

Thanks

**Comment by SSEKPIUS** [comment]
> 

@tresorsawasawa , kindly note, am having no update on my dashboard, the task is still pending review, could you advise, please

**Comment by tresorsawasawa** [comment]
Hi @SSEKPIUS

Your review will appear soon. I noticed some issues before submitting your review.

Sorry for that.

**Review by tresorsawasawa — CHANGES_REQUESTED** [review]
# STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @SSEKPIUS ,:wave: :wave: 
While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🛑 🛑

You have submitted a project where Linters are not correctly set up. You used the wrong `.github/workflows/linters.yml` file content as result no checks for `.eslintrc`  on GitHub. You can find the correct config content on **[this repository](https://github.com/microverseinc/linters-config/tree/master/html-css-js)**.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

---
Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

---
_Invalid Code Review Request **Does not count** into the code reviews limit._

**Review by omar-muhamad — COMMENTED** [review]
# Invalid ❌

Hi @SSEKPIUS,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

Your Code Review Request is marked as invalid for these reasons:

- [ ] As requested by the previous reviewer, You have submitted a project where Linters are not correctly set up. You used the wrong .github/workflows/linters.yml file content as result no checks for .eslintrc on GitHub. You can find the correct config content on [this repository](https://github.com/microverseinc/linters-config/tree/master/html-css-js).

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

**Pull request closed without merging**
